# Generated by Django 4.1.7 on 2024-03-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChattingDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('reciever', models.CharField(default=None, max_length=20)),
                ('msg', models.CharField(max_length=200)),
                ('yop', models.IntegerField(default=0)),
                ('msgseen', models.BooleanField(default=False)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('enroll', models.CharField(max_length=20)),
                ('YOP', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=10)),
            ],
        ),
    ]
