# Generated by Django 5.0.6 on 2024-05-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
