# Generated by Django 5.0.6 on 2024-05-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_signup_email_alter_signup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocks',
            name='status',
        ),
        migrations.AddField(
            model_name='blocks',
            name='Reason',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
    ]
