# Generated by Django 3.2 on 2024-05-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_remove_blocks_status_blocks_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocks',
            name='role',
            field=models.CharField(default=111, max_length=20),
            preserve_default=False,
        ),
    ]
