# Generated by Django 3.2 on 2024-05-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_blocks_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='role',
            field=models.CharField(max_length=40),
        ),
    ]
